version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: olive_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: olivepwd
      POSTGRES_DB: olive_product_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: